/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.googleApi;

import Business.LatLong;
import Business.WorkQueue.BeneficiaryWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author pooji
 */
public class DistanceJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
    /**
     * Creates new form DistanceJPanel
     */
    public DistanceJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
       // populateTable();
    }
    
    public void populateTable(String name, double distance){
         DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();
        
        model.setRowCount(0);
        
      
            Object[] row = new Object[2];
            row[0] = name;
            row[1] = distance;
           
            model.addRow(row);
           
           
        
        
      // String url= "https://www.google.com/maps/search/homeless+in+boston/@42.3499255,-71.0706883,15z";
    }
//    public void populateDistance(Position d1){
//      //  Location l= new Location();
//        
//        Position d2= new Position();
//        d2.setLatitude();
//        d2.setLongitude();
//        d2.setName("d");
//        
//        double distance= Math.sqrt(Math.pow((d1.getLatitude()-d2.getLatitude()),2) - Math.pow((d1.getLongitude()-d2.getLongitude()),2));
//         distance= Math.sqrt(((d1.getLatitude()-d2.getLatitude())*(d1.getLatitude()-d2.getLatitude())) - ((d1.getLongitude()-d2.getLongitude())*(d1.getLongitude()-d2.getLongitude())))*1000000;
//        double distances= distance(d1.getLatitude(),d1.getLongitude(),d2.getLatitude(),d2.getLongitude(),'M');
//        populateTable(d2.getName(),distances);
//    }
     public void populateDistance(LatLong p1) {
        double lat1= p1.getLatitude();
        double lon1=p1.getLongitude();
        double lat2=42.347929;
        double lon2=-71.065111;
  double theta = lon1 - lon2;
  double dist = Math.sin(deg2rad(lat1)) * Math.sin(deg2rad(lat2)) + Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * Math.cos(deg2rad(theta));
  dist = Math.acos(dist);
  dist = rad2deg(dist);
  dist = dist * 60 * 1.1515;
  populateTable("a",dist);
    }
    private double deg2rad(double deg) {
  return (deg * Math.PI / 180.0);
}
    private double rad2deg(double rad) {
  return (rad * 180.0 / Math.PI);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoc1 = new javax.swing.JButton();
        btnLoc6 = new javax.swing.JButton();
        btnLoc5 = new javax.swing.JButton();
        btnLoc4 = new javax.swing.JButton();
        btnLoc2 = new javax.swing.JButton();
        btnLoc3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDistance = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoc1.setText("Location 1");
        btnLoc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc1ActionPerformed(evt);
            }
        });
        add(btnLoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 101, -1, -1));

        btnLoc6.setText("Location 6");
        btnLoc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc6ActionPerformed(evt);
            }
        });
        add(btnLoc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 219, -1, -1));

        btnLoc5.setText("Location 5");
        btnLoc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc5ActionPerformed(evt);
            }
        });
        add(btnLoc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 343, -1, -1));

        btnLoc4.setText("Location 4");
        btnLoc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc4ActionPerformed(evt);
            }
        });
        add(btnLoc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 343, -1, -1));

        btnLoc2.setText("Location 2");
        btnLoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc2ActionPerformed(evt);
            }
        });
        add(btnLoc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 101, -1, -1));

        btnLoc3.setText("Location 3");
        btnLoc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoc3ActionPerformed(evt);
            }
        });
        add(btnLoc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 219, -1, -1));

        tblDistance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Distance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDistance);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 101, 260, 343));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc1ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(42.347929);
        p1.setLongitude(-71.065111);
        p1.setName("p1");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc1ActionPerformed

    private void btnLoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc2ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(42.345501);
        p1.setLongitude(-71.070273);
        p1.setName("p2");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc2ActionPerformed

    private void btnLoc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc6ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(42.356987);
        p1.setLongitude(-71.057412);
        p1.setName("p6");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc6ActionPerformed

    private void btnLoc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc3ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(42.341012);
        p1.setLongitude(-71.084596);
        p1.setName("p3");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc3ActionPerformed

    private void btnLoc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc5ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(43.347929);
        p1.setLongitude(-70.065111);
        p1.setName("p5");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc5ActionPerformed

    private void btnLoc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoc4ActionPerformed
        // TODO add your handling code here:
        LatLong p1= new LatLong();
        p1.setLatitude(42.347929);
        p1.setLongitude(-71.065111);
        p1.setName("p4");
        populateDistance(p1);
    }//GEN-LAST:event_btnLoc4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc1;
    private javax.swing.JButton btnLoc2;
    private javax.swing.JButton btnLoc3;
    private javax.swing.JButton btnLoc4;
    private javax.swing.JButton btnLoc5;
    private javax.swing.JButton btnLoc6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDistance;
    // End of variables declaration//GEN-END:variables
}
