/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.googleApi;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.LatLong;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author pooji
 */
public class HomelessFoundJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomelessFoundJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    StateNetwork state;
    CountryNetwork country;
    EcoSystem system;
    final Browser browser;
    BrowserView view;
    LatLong latLong;
    Organization organization;

    public HomelessFoundJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, StateNetwork state, CountryNetwork country, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.state = state;
        this.country = country;
        this.system = system;
        this.organization = organization;
        latLong = new LatLong();
        browser = new Browser();
        view = new BrowserView(browser);
        //Loading the google maps
        browser.loadURL("https://www.google.com/maps");
        this.mapContainer.add(view, "a");
        this.mapContainer.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        mapContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLocation = new javax.swing.JButton();

        jSplitPane2.setDividerLocation(800);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        mapContainer.setLayout(new java.awt.CardLayout());
        jSplitPane2.setTopComponent(mapContainer);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLocation.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 14)); // NOI18N
        btnLocation.setText("Set Location");
        btnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationActionPerformed(evt);
            }
        });
        jPanel1.add(btnLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jSplitPane2.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed
        // TODO add your handling code here:
        try {
            if (browser.getURL() != null) {
                //Retrieving the url from the browser and splitting to get the Latitude and Longitude
                String[] a = browser.getURL().split("!3d", 0);
                if (a[1] != null) {
                    String[] b = a[1].split("!4d");
                    double lat = Double.parseDouble(b[0]);
                    double lon = Double.parseDouble(b[1]);
                    latLong.setLatitude(lat);
                    latLong.setLongitude(lon);
                } else {
                    JOptionPane.showMessageDialog(null, "Set the Location");
                }
            }
            RequestShelterJPanel manageOrganizationJPanel = new RequestShelterJPanel(userProcessContainer, account, organization, enterprise, state, country, system, latLong);
            userProcessContainer.add("RequestShelterJPanel", manageOrganizationJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Set the Location first");
        }
    }//GEN-LAST:event_btnLocationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLocation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel mapContainer;
    // End of variables declaration//GEN-END:variables
}
